train_manifest: ???
val_manifest: ???
model:
    mid_layers: 1
    input_size: 64
    audio_conf:
        window: hamming
        window_stride: 0.01
        window_size: 0.02
        sample_rate: 16000
    labels: english_lowercase
    decoder:
        _target_: decoder.GreedyDecoder
        labels: ${model.labels}
    optimizer:
        _target_: torch.optim.SGD
        lr: 1e-5
        momentum: 0.9
        nesterov: True
        weight_decay: 1e-5
trainer:
    default_root_dir: .
    max_epochs: 5
    max_steps: null
    gpus: 0
    
hydra:
    run:
        dir: ${trainer.default_root_dir}
    job_logging:
        root:
            handlers: null