# @package model
optimizer:
    _target_: torch.optim.SGD
    lr: 1e-5 
    momentum: 0.9
    nesterov: True
    weight_decay: 1e-5
scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 1
#scheduler:
#    _target_: torch.optim.lr_scheduler.OneCycleLR
#    max_lr: ${model.optimizer.lr}
#    total_steps: ${trainer.max_steps} 
