defaults:
    - audio: standard_16k
    - optimizer: exp_lr_optimizer
data:
    train_manifest: ???
    val_manifest: ???
    batch_size: 4
    mel_spec: ${model.input_size}
    audio_conf: ${model.audio_conf}
model:
    mid_layers: 1
    input_size: 64
    layers:
     - output_size: 256
       kernel_size: 11
       stride: 2
       dilation: 1
       dropout: 0.2
     - output_size: 256
       kernel_size: 11
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 256
       kernel_size: 11
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 256
       kernel_size: 11
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 384
       kernel_size: 13
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 384
       kernel_size: 13
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 384
       kernel_size: 13
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 512
       kernel_size: 17
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 512
       kernel_size: 17
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 512
       kernel_size: 17
       stride: 1
       dilation: 1
       dropout: 0.2
     - output_size: 640
       kernel_size: 21
       stride: 1
       dilation: 1
       dropout: 0.3
     - output_size: 640
       kernel_size: 21
       stride: 1
       dilation: 1
       dropout: 0.3
     - output_size: 640
       kernel_size: 21
       stride: 1
       dilation: 1
       dropout: 0.3
     - output_size: 768
       kernel_size: 25
       stride: 1
       dilation: 1
       dropout: 0.3
     - output_size: 768
       kernel_size: 25
       stride: 1
       dilation: 1
       dropout: 0.3
     - output_size: 768
       kernel_size: 25
       stride: 1
       dilation: 1
       dropout: 0.3
     - output_size: 896
       kernel_size: 29
       stride: 1
       dilation: 2
       dropout: 0.4
     - output_size: 896
       kernel_size: 29
       stride: 1
       dilation: 2
       dropout: 0.4
     - output_size: 896
       kernel_size: 29
       stride: 1
       dilation: 2
       dropout: 0.4
     - output_size: 1024
       kernel_size: 1
       stride: 1
       dilation: 1
       dropout: 0.4 
    audio_conf:
        window: hamming
        window_stride: 0.01
        window_size: 0.02
        sample_rate: 16000
    labels: english_lowercase
    decoder:
        _target_: decoder.GreedyDecoder
        labels: ${model.labels}
    # optimizer:
    #     _target_: torch.optim.SGD
    #     lr: 1e-5 
    #     momentum: 0.9
    #     nesterov: True
    #     weight_decay: 1e-5
    # scheduler:
    #     _target_: torch.optim.lr_scheduler.ExponentialLR
    #     gamma: 0.999
    #scheduler:
    #    _target_: torch.optim.lr_scheduler.OneCycleLR
    #    max_lr: ${model.optimizer.lr}
    #    total_steps: ${trainer.max_steps}
         
trainer:
    default_root_dir: .
    max_epochs: 5
    max_steps: null
    gpus: 0
    
hydra:
    run:
        dir: ${trainer.default_root_dir}
    job_logging:
        root:
            handlers: null