defaults:
    - audio: standard_16k
    - optimizer: const_lr_optimizer
    - model: wav2letter
data:
    train_manifest: ???
    val_manifest: ???
    batch_size: 4
    mel_spec: ${model.input_size}
    audio_conf: ${model.audio_conf}
model:
    input_size: 64
    labels: english
    print_decoded_prob: 0
    decoder:
        _target_: decoder.GreedyDecoder
        labels: ${model.labels}
trainer:
    default_root_dir: .
    max_epochs: 5
    max_steps: -1
    gpus: 0
    
hydra:
    run:
        dir: ${trainer.default_root_dir}
    job_logging:
        root:
            handlers: null
